# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re, os


class Case2016(unittest.TestCase):
    def setUp(self):
        option = webdriver.ChromeOptions()
        executable_path = "C:\\Users\\admin\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe"
        os.environ['webdriver.chrome.driver'] = executable_path
        self.driver = webdriver.Chrome(executable_path, chrome_options=option)
        self.driver.implicitly_wait(30)
        self.base_url = "http://124.115.106.140:7001/manage/user/home"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_case2016(self):
        driver = self.driver
        driver.get(self.base_url + "/manage/user/home")
        driver.maximize_window()
        driver.find_element_by_id("userNameCopy").clear()
        driver.find_element_by_id("userNameCopy").send_keys("admin")
        driver.find_element_by_id("userPassword").clear()
        driver.find_element_by_id("userPassword").send_keys("666666")
        driver.find_element_by_id("btnLogin").click()
        driver.find_element_by_css_selector("li.unnum4").click()
        driver.find_element_by_id("menu-sm1").click()
        driver.find_element_by_id("second-10").click()
        driver.find_element_by_id("menuli10").click()
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"八塌湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年八塌湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"陈家坡村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年陈家坡村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"东街村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年东街村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"樊河畔村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年樊河畔村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"方渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年方渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高梁村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年高梁村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高沙沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年高沙沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"葛村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年葛村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"河上村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年河上村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"红柳滩村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年红柳滩村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"候渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年候渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"花渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年花渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"街上村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年街上村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘家湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年刘家湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘兴庄村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年刘兴庄村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"柳湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年柳湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"芦草沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年芦草沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"庙湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年庙湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"南洼村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年南洼村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"秦山村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年秦山村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"石崖底村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年石崖底村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"寺沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年寺沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"田寨瓦村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年田寨瓦村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"瓦岗寨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年瓦岗寨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西街村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年西街村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨正沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年杨正沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨庄村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年杨庄村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"张硷村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年张硷村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"赵山村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年赵山村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周圪坨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年周圪坨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年周沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"朱家寨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年朱家寨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西环路社区")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2016年西环路社区有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.switch_to_default_content()
        driver.find_element_by_link_text(u"退出").click()

    def is_element_present(self, how, what):
        try:
            self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e:
            return False
        return True

    def is_alert_present(self):
        try:
            self.driver.switch_to_alert()
        except NoAlertPresentException as e:
            return False
        return True

    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally:
            self.accept_next_alert = True

    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)


if __name__ == "__main__":
    unittest.main()
