# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re,os

class UntitledTestCase(unittest.TestCase):
    def setUp(self):
        option = webdriver.ChromeOptions()
        executable_path = "C:\\Users\\admin\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe"
        os.environ['webdriver.chrome.driver'] = executable_path
        self.driver = webdriver.Chrome(executable_path, chrome_options=option)
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.katalon.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_untitled_test_case(self):
        driver = self.driver
        driver.get("http://124.115.106.140:7001/manage/user/home")
        driver.maximize_window()
        driver.find_element_by_id("userNameCopy").click()
        driver.find_element_by_id("userNameCopy").clear()
        driver.find_element_by_id("userNameCopy").send_keys("admin")
        driver.find_element_by_id("userPassword").click()
        driver.find_element_by_id("userPassword").clear()
        driver.find_element_by_id("userPassword").send_keys("1")
        driver.find_element_by_id("btnLogin").click()
        driver.find_element_by_css_selector("li.unnum4").click()
        driver.find_element_by_id("menu-sm3").click()
        driver.find_element_by_id("second-31").click()
        driver.find_element_by_css_selector("#level-31 > ul > #menuli11").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=0 | ]]
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        driver.find_element_by_name("town").click()
        driver.find_element_by_name("town").click()
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"八塌湾村委会")
        driver.find_element_by_css_selector("option[value=\"610802028001\"]").click()
        driver.find_element_by_id("teamId").click()
        driver.find_element_by_id("teamId").click()
        driver.find_element_by_name("leadResult").click()
        driver.find_element_by_name("leadResult").click()
        driver.find_element_by_name("poorAttri").click()
        driver.find_element_by_name("poorAttri").click()
        driver.find_element_by_name("identify").click()
        driver.find_element_by_name("identify").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"未脱贫")
        driver.find_element_by_css_selector("option[value=\"0\"]").click()
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"全部")
        driver.find_element_by_css_selector("#villageId > option").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"已脱贫（享受政策）")
        driver.find_element_by_css_selector("option[value=\"1\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"预脱贫")
        driver.find_element_by_css_selector("option[value=\"2\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"返贫")
        driver.find_element_by_css_selector("option[value=\"3\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"已脱贫（不再享受政策）")
        driver.find_element_by_css_selector("option[value=\"4\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"未脱贫")
        driver.find_element_by_css_selector("option[value=\"0\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text(u"已设置")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option[value=\"1\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text(u"未设置")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option[value=\"0\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text(u"已设置")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option[value=\"1\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text("")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option").click()
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"八塌湾村委会")
        driver.find_element_by_css_selector("option[value=\"610802028001\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“八塌湾村委会”查看未脱贫人数为%d"%int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"陈家坡村委会")
        driver.find_element_by_css_selector("option[value=\"610802028002\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“陈家坡村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"东街村委会")
        driver.find_element_by_css_selector("option[value=\"610802028003\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“东街村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"樊河畔村委会")
        driver.find_element_by_css_selector("option[value=\"610802028004\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“樊河畔村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"方渠村委会")
        driver.find_element_by_css_selector("option[value=\"610802028005\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“方渠村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高梁村委会")
        driver.find_element_by_css_selector("option[value=\"610802028006\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“高梁村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高沙沟村委会")
        driver.find_element_by_css_selector("option[value=\"610802028007\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“高沙沟村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"葛村委会")
        driver.find_element_by_css_selector("option[value=\"610802028008\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“葛村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"河上村委会")
        driver.find_element_by_css_selector("option[value=\"610802028009\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“河上村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"红柳滩村委会")
        driver.find_element_by_css_selector("option[value=\"610802028010\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“红柳滩村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"候渠村委会")
        driver.find_element_by_css_selector("option[value=\"610802028011\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“候渠村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"花渠村委会")
        driver.find_element_by_css_selector("option[value=\"610802028012\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“花渠村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"街上村委会")
        driver.find_element_by_css_selector("option[value=\"610802028013\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“街上村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘家湾村委会")
        driver.find_element_by_css_selector("option[value=\"610802028014\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“刘家湾村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘兴庄村委会")
        driver.find_element_by_css_selector("option[value=\"610802028015\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“刘兴庄村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"柳湾村委会")
        driver.find_element_by_css_selector("option[value=\"610802028016\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“柳湾村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"芦草沟村委会")
        driver.find_element_by_css_selector("option[value=\"610802028017\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“芦草沟村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"庙湾村委会")
        driver.find_element_by_css_selector("option[value=\"610802028018\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“庙湾村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"南洼村委会")
        driver.find_element_by_css_selector("option[value=\"610802028019\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“南洼村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"秦山村委会")
        driver.find_element_by_css_selector("option[value=\"610802028020\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“秦山村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"石崖底村委会")
        driver.find_element_by_css_selector("option[value=\"610802028021\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“石崖底村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"寺沟村委会")
        driver.find_element_by_css_selector("option[value=\"610802028022\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“寺沟村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"田寨瓦村委会")
        driver.find_element_by_css_selector("option[value=\"610802028023\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“田寨瓦村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"瓦岗寨村委会")
        driver.find_element_by_css_selector("option[value=\"610802028024\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“瓦岗寨村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西街村委会")
        driver.find_element_by_css_selector("option[value=\"610802028025\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“西街村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨正沟村委会")
        driver.find_element_by_css_selector("option[value=\"610802028026\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“杨正沟村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨庄村委会")
        driver.find_element_by_css_selector("option[value=\"610802028027\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“杨庄村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"张硷村委会")
        driver.find_element_by_css_selector("option[value=\"610802028028\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“张硷村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"赵山村委会")
        driver.find_element_by_css_selector("option[value=\"610802028029\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“赵山村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周圪坨村委会")
        driver.find_element_by_css_selector("option[value=\"610802028030\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“周圪坨村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周沟村委会")
        driver.find_element_by_css_selector("option[value=\"610802028031\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“周沟村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"朱家寨村委会")
        driver.find_element_by_css_selector("option[value=\"610802028032\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“朱家寨村委会”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("villageId").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西环路社区")
        driver.find_element_by_css_selector("option[value=\"61080202803300\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按所在村“西环路社区”查看未脱贫人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | relative=parent | ]]
        driver.switch_to_default_content()
        driver.find_element_by_link_text(u"退出").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
