# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re,os

class UntitledTestCase(unittest.TestCase):
    def setUp(self):
        option = webdriver.ChromeOptions()
        executable_path = "C:\\Users\\admin\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe"
        os.environ['webdriver.chrome.driver'] = executable_path
        self.driver = webdriver.Chrome(executable_path, chrome_options=option)
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.katalon.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_untitled_test_case(self):
        driver = self.driver
        driver.get("http://124.115.106.140:7001/manage/user/home")
        driver.maximize_window()
        driver.find_element_by_id("userNameCopy").click()
        driver.find_element_by_id("userNameCopy").clear()
        driver.find_element_by_id("userNameCopy").send_keys("admin")
        driver.find_element_by_id("userPassword").click()
        driver.find_element_by_id("userPassword").clear()
        driver.find_element_by_id("userPassword").send_keys("1")
        driver.find_element_by_id("btnLogin").click()
        driver.find_element_by_css_selector("li.unnum4").click()
        driver.find_element_by_id("menu-sm4").click()
        driver.find_element_by_id("second-41").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=0 | ]]
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        driver.find_element_by_name("town").click()
        driver.find_element_by_id("villageId").click()
        driver.find_element_by_id("villageId").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"未脱贫")
        driver.find_element_by_css_selector("option[value=\"0\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按脱贫状态“未脱贫”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"已脱贫（享受政策）")
        driver.find_element_by_css_selector("option[value=\"1\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按脱贫状态“已脱贫（享受政策）”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"预脱贫")
        driver.find_element_by_css_selector("option[value=\"2\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按脱贫状态“预脱贫”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"返贫")
        driver.find_element_by_css_selector("option[value=\"3\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按脱贫状态“返贫”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("tpAttri").click()
        Select(driver.find_element_by_name("tpAttri")).select_by_visible_text(u"已脱贫（不再享受政策）")
        driver.find_element_by_css_selector("option[value=\"4\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按脱贫状态“已脱贫（不再享受政策）”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"因病")
        driver.find_element_by_css_selector("option[value=\"01\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“因病”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"因残")
        driver.find_element_by_css_selector("option[value=\"02\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“因残”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"因学")
        driver.find_element_by_css_selector("option[value=\"03\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“因学”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"因灾")
        driver.find_element_by_css_selector("option[value=\"04\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“因灾”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"缺土地")
        driver.find_element_by_css_selector("option[value=\"05\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“缺土地”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"缺水")
        driver.find_element_by_css_selector("option[value=\"06\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“缺水”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"缺技术")
        driver.find_element_by_css_selector("option[value=\"07\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“缺技术”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"缺劳力")
        driver.find_element_by_css_selector("option[value=\"08\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“缺劳力”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"缺资金")
        driver.find_element_by_css_selector("option[value=\"09\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“缺资金”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"交通条件落后")
        driver.find_element_by_css_selector("option[value=\"10\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“交通条件落后”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"自身发展动力不足")
        driver.find_element_by_css_selector("option[value=\"11\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“自身发展动力不足”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("leadResult").click()
        Select(driver.find_element_by_name("leadResult")).select_by_visible_text(u"其他")
        driver.find_element_by_css_selector("option[value=\"99\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按主要致贫原因“其他”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"一般贫困户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"01\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“一般贫困户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"低保户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"02\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“低保户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"五保户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"03\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“五保户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"低保贫困户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"04\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“低保贫困户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"一般农户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"05\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“一般农户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("poorAttri").click()
        Select(driver.find_element_by_name("poorAttri")).select_by_visible_text(u"五保贫困户")
        driver.find_element_by_css_selector("select[name=\"poorAttri\"] > option[value=\"06\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困户属性“五保贫困户”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("identify").click()
        Select(driver.find_element_by_name("identify")).select_by_visible_text(u"国家标准")
        driver.find_element_by_css_selector("select[name=\"identify\"] > option[value=\"01\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按识别标准“国家标准”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("identify").click()
        Select(driver.find_element_by_name("identify")).select_by_visible_text(u"省定标准")
        driver.find_element_by_css_selector("select[name=\"identify\"] > option[value=\"02\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按识别标准“省定标准”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("identify").click()
        Select(driver.find_element_by_name("identify")).select_by_visible_text(u"市定标准")
        driver.find_element_by_css_selector("select[name=\"identify\"] > option[value=\"03\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按识别标准“市定标准”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("userName").click()
        driver.find_element_by_name("userName").clear()
        driver.find_element_by_name("userName").send_keys(u"高")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困人口姓名“高”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("userName").click()
        driver.find_element_by_name("userName").clear()
        driver.find_element_by_name("userName").send_keys(u"高芝英")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按贫困人口姓名“高芝英”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("cardNo").click()
        driver.find_element_by_name("cardNo").clear()
        driver.find_element_by_name("cardNo").send_keys("6127211928")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按证件号码“6127211928”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text(u"未设置")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option[value=\"0\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按帮扶责任人设置“未设置”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("hasnotHelpPerson").click()
        Select(driver.find_element_by_name("hasnotHelpPerson")).select_by_visible_text(u"已设置")
        driver.find_element_by_css_selector("select[name=\"hasnotHelpPerson\"] > option[value=\"1\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按帮扶责任人设置“已设置”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_id("helpPersonName").click()
        driver.find_element_by_id("helpPersonName").clear()
        driver.find_element_by_id("helpPersonName").send_keys(u"刘")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按帮扶责任人姓名“刘”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_id("helpPersonName").click()
        driver.find_element_by_id("helpPersonName").clear()
        driver.find_element_by_id("helpPersonName").send_keys(u"王")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按帮扶责任人姓名“王”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_id("helpPersonName").click()
        driver.find_element_by_id("helpPersonName").clear()
        driver.find_element_by_id("helpPersonName").send_keys(u"王均")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按帮扶责任人姓名“王均”查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        driver.find_element_by_name("queryMyObject").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按我帮扶的贫困户，查看人数为%d" % int(value))
        driver.find_element_by_id("resetBtn").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | relative=parent | ]]
        driver.switch_to_default_content()
        driver.find_element_by_link_text(u"退出").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
