# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re,os

class UntitledTestCase(unittest.TestCase):
    def setUp(self):
        option = webdriver.ChromeOptions()
        executable_path = "C:\\Users\\admin\\AppData\\Local\\Google\\Chrome\\Application\\chromedriver.exe"
        os.environ['webdriver.chrome.driver'] = executable_path
        self.driver = webdriver.Chrome(executable_path, chrome_options=option)
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.katalon.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_untitled_test_case(self):
        driver = self.driver
        driver.get("http://124.115.106.140:7001/manage/user/home")
        driver.maximize_window()
        driver.find_element_by_id("userNameCopy").click()
        driver.find_element_by_id("userNameCopy").clear()
        driver.find_element_by_id("userNameCopy").send_keys("admin")
        driver.find_element_by_id("userPassword").click()
        driver.find_element_by_id("userPassword").clear()
        driver.find_element_by_id("userPassword").send_keys("1")
        driver.find_element_by_id("btnLogin").click()
        driver.find_element_by_css_selector("li.unnum4").click()
        driver.find_element_by_id("menu-sm6").click()
        driver.find_element_by_id("second-63").click()
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=0 | ]]
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"八塌湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年八塌湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"陈家坡村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年陈家坡村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"东街村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年东街村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"樊河畔村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年樊河畔村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"方渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年方渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高梁村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年高梁村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"高沙沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年高沙沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"葛村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年葛村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"河上村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年河上村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"红柳滩村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年红柳滩村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"候渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年候渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"花渠村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年花渠村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"街上村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年街上村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘家湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年刘家湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"刘兴庄村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年刘兴庄村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"柳湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年柳湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"芦草沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年芦草沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"庙湾村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年庙湾村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"南洼村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年南洼村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"秦山村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年秦山村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"石崖底村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年石崖底村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"寺沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年寺沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"田寨瓦村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年田寨瓦村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"瓦岗寨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年瓦岗寨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西街村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年西街村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨正沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年杨正沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"杨庄村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年杨庄村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"张硷村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年张硷村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"赵山村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年赵山村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周圪坨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年周圪坨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"周沟村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年周沟村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"朱家寨村委会")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年朱家寨村委会有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        Select(driver.find_element_by_id("villageId")).select_by_visible_text(u"西环路社区")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("2017年西环路社区有%d家贫困户" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        #按项目类型查询
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"教育（补助）培训")
        driver.find_element_by_css_selector("option[value=\"10\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'教育（补助）培训'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"易地扶贫搬迁")
        driver.find_element_by_css_selector("option[value=\"20\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'易地扶贫搬迁'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"金融扶贫")
        driver.find_element_by_css_selector("option[value=\"30\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'金融扶贫'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"产业扶贫")
        driver.find_element_by_css_selector("option[value=\"40\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'产业扶贫'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"整村推进")
        driver.find_element_by_css_selector("option[value=\"50\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'整村推进'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectType").click()
        Select(driver.find_element_by_name("projectType")).select_by_visible_text(u"基础设施")
        driver.find_element_by_css_selector("option[value=\"70\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目类型'基础设施'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        #按项目子类型查询
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"高校学历教育补助")
        driver.find_element_by_css_selector("option[value=\"101\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"职业高等学历教育补助")
        driver.find_element_by_css_selector("option[value=\"102\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"职业中等学历教育补助")
        driver.find_element_by_css_selector("option[value=\"103\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"劳动力短期技能培训")
        driver.find_element_by_css_selector("option[value=\"104\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"农民实用技术培训")
        driver.find_element_by_css_selector("option[value=\"105\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"雨露计划")
        driver.find_element_by_css_selector("option[value=\"106\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"致富带头人创业培训")
        driver.find_element_by_css_selector("option[value=\"107\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"实用技术培训")
        driver.find_element_by_css_selector("option[value=\"108\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"集中安置")
        driver.find_element_by_css_selector("option[value=\"201\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"分散安置")
        driver.find_element_by_css_selector("option[value=\"202\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"(扶贫)小额信贷贴息")
        driver.find_element_by_css_selector("option[value=\"301\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"扶贫龙头企业贴息")
        driver.find_element_by_css_selector("option[value=\"302\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"其他")
        driver.find_element_by_css_selector("option[value=\"303\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"合作社")
        driver.find_element_by_css_selector("option[value=\"304\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"农业保险(产业保险)")
        driver.find_element_by_css_selector("option[value=\"305\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"人身保险(提供本省资金管理办法)")
        driver.find_element_by_css_selector("option[value=\"306\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"产业项目")
        driver.find_element_by_css_selector("option[value=\"401\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"资产收益扶贫")
        driver.find_element_by_css_selector("option[value=\"402\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"整村推进项目")
        driver.find_element_by_css_selector("option[value=\"501\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"直补到户")
        driver.find_element_by_css_selector("option[value=\"601\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectSType").click()
        Select(driver.find_element_by_name("projectSType")).select_by_visible_text(u"基础设施建设")
        driver.find_element_by_css_selector("option[value=\"701\"]").click()
        driver.find_element_by_id("queryBtn").click()
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        #项目过程
        driver.find_element_by_name("projectSType").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目新建")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"10\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目新建'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目申请")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"20\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目申请'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目审核并实施")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"30\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目审核并实施'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目验收")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"40\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目验收'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目完成")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"50\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目完成'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目检查")
        driver.find_element_by_css_selector("option[value=\"60\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目检查'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("projectState").click()
        Select(driver.find_element_by_name("projectState")).select_by_visible_text(u"项目支付")
        driver.find_element_by_css_selector("select[name=\"projectState\"] > option[value=\"70\"]").click()
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按项目过程'项目支付'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        #按时间查询
        driver.find_element_by_id("startDate").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | relative=parent | ]]
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=1 | ]]
        driver.switch_to_default_content()
        driver.switch_to_frame(driver.find_element_by_xpath("/html/body/div[1]/iframe"))
        driver.find_element_by_xpath("/html/body/div/div[1]/div[1]/a").click()
        driver.find_element_by_xpath("/html/body/div/div[1]/div[1]/a").click()
        driver.switch_to_default_content()
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | relative=parent | ]]
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=1 | ]]
        driver.find_element_by_id("endDate").click()
        driver.switch_to_default_content()
        driver.switch_to_frame(driver.find_element_by_xpath("/html/body/div[1]/iframe"))
        driver.find_element_by_xpath("/html/body/div/div[3]/table/tbody/tr[2]/td[2]").click()
        driver.switch_to_default_content()
        driver.switch_to_frame(driver.find_element_by_class_name("iframeClass"))
        driver.find_element_by_id("queryBtn").click()
        #按检查人查询
        driver.find_element_by_name("userName").click()
        driver.find_element_by_name("userName").clear()
        driver.find_element_by_name("userName").send_keys(u"张")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按检查人关键字'张'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("userName").click()
        driver.find_element_by_name("userName").clear()
        driver.find_element_by_name("userName").send_keys(u"刘")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按检查人关键字'刘'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        driver.find_element_by_name("userName").click()
        driver.find_element_by_name("userName").clear()
        driver.find_element_by_name("userName").send_keys(u"王")
        driver.find_element_by_id("queryBtn").click()
        value = driver.find_element_by_id("totalNum").get_attribute("value")
        print("按检查人关键字'王'查询到%d个结果：" % int(value))
        driver.find_element_by_xpath(u"//button[@value='重置']").click()
        # ERROR: Caught exception [ERROR: Unsupported command [selectFrame | relative=parent | ]]
        driver.switch_to_default_content()
        driver.find_element_by_link_text(u"退出").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
